### ISSUE TITLE
unknown format \"int32\"

### ISSUE THREAD

**Issue by teone** [ninofiliu/oa-client#12]
Hi there,
first of all thanks for the library!

While integrating our APIs I noticed this error while trying to save models that have a `format` field in the OpenAPI specs

```
{ "name": "Error", "message": "unknown format \"int32\" is used in schema at path \"#/properties/state/properties/ifindex\"", ...}
```

For example the above error happens on:
```
Foo:
      properties:
        ifindex:
          format: int32
          minimum: 0
          title: ifindex
          type: integer
```

I think that is due to relying on an older version of `ajv (6.12.2)` while I believe `8.11.0` supports the OpenApi formats https://ajv.js.org/packages/ajv-formats.html 

Is there any interest in updating the library? If so I can probably look into it.

PS: for now I can workaround this issue by setting `validationLevel: 'off'` when creating the client

**Comment by ninofiliu** [comment]
Thanks for the interest & the detailed bug report!

I haven't touched the codebase in months (I'm still maintening the whole thing but it just worked so I didn't touch anything) so it might just be some deps that need some updating

I'll look into that this week!

**Comment by ninofiliu** [comment]
If you can provide an [MRE](https://stackoverflow.com/help/minimal-reproducible-example) that'd be cool

**Comment by ninofiliu** [comment]
nvm I got it, should be fixed in oa-client@0.9.0 (latest)

I'll let you close the issue if that's good for you!

**Comment by teone** [comment]
thanks! You were faster in providing the solution that me in providing the example: https://codesandbox.io/s/oa-client-format-86crg2 😄 

I just tried it out and it's working as expected.

One side-effect is that now `ajv` has `strict: true` by default, so it complains about extra arguments in the OpenApi specs like:
```
strict mode: unknown keyword: "x-list-multiple"
```
for a spec that looks like:
```
Foo:
      properties:
        bar:
          title: bar
          type: integer
      title: Foo
      type: object
      x-list-multiple: true
```
but don't worry about it, I might come back with a PR for that
